abbreviations_diagnosis = [
    {"label": "Schizophrenia", "abbreviations": ["SZ", "SP", "SZD"]},
    {"label": "Bipolar disorder", "abbreviations": ["BD", "BPI"]},
    {
        "label": "Attention deficit hyperactivity disorder",
        "abbreviations": ["ADHD", "ADHD-PI", "ADHD-C"],
    },
    {"label": "Separation anxiety", "abbreviations": ["SAD", "SAS"]},
    {"label": "Generalized anxiety disorder", "abbreviations": ["GAD", "GAN"]},
    {"label": "Social phobia", "abbreviations": ["SAD", "SPS", "SPH"]},
    {"label": "Major depressive disorder", "abbreviations": ["MDD"]},
    {
        "label": "Autism spectrum disorder",
        "abbreviations": ["ASD", "AS", "ASDs"],
    },
    {"label": "Overweight", "abbreviations": ["OW", "BW"]},
    {"label": "Parkinson's disease", "abbreviations": ["PD", "PDx", "PDs"]},
    {"label": "Traumatic brain injury", "abbreviations": ["TBI", "TBI-SCI"]},
    {"label": "Obsessive-compulsive disorder", "abbreviations": ["OCD"]},
    {"label": "Fibromyalgia", "abbreviations": ["FM"]},
    {"label": "Visual impairment", "abbreviations": ["VI", "VIa", "VA"]},
    {"label": "Depressive disorder", "abbreviations": ["MDD", "DD"]},
    {"label": "Dysthymia", "abbreviations": ["DYSM", "DD"]},
    {"label": "Mood disorder", "abbreviations": ["MDD", "MD"]},
    {"label": "Dyslexia", "abbreviations": ["ID", "IDR", "DLX", "dys."]},
    {"label": "Specific spelling disorder", "abbreviations": ["SSD"]},
    {
        "label": "Mental disorder",
        "abbreviations": ["MD", "MDD", "BD", "PD", "MPD"],
    },
    {"label": "Anxiety disorder", "abbreviations": ["AD"]},
    {"label": "Concussion injury of brain", "abbreviations": ["CI"]},
    {"label": "Moderate depression", "abbreviations": ["MDD", "MODD"]},
    {"label": "Mild depression", "abbreviations": ["MD"]},
    {"label": "Aphasia", "abbreviations": ["AS", "AP", "Aphas."]},
]
