name: Codespell

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with: 
          skip: ./app/term_url_processing/abbreviations/abbreviations_sex.py,./app/term_url_processing/abbreviations/abbreviations_diagnosis.py,./app/term_url_processing/abbreviations/abbreviations_assessment.py,./app/term_url_processing/abbreviations/abbreviations_image_modality.py